"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { usePathname } from "next/navigation";
import { createClient } from "@/utils/supabase/client";
import { createContext, useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Create a context for the user
export const UserContext = createContext<any>(null);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const supabase = createClient();

  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    if (pathname === "/login" || pathname === "/signup") return;
    const fetchUser = async () => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      setUser(user);
    };
    fetchUser();
  }, [supabase]);

  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <UserContext.Provider value={user}>{children}</UserContext.Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
